# Generated by Django 3.0.3 on 2020-03-20 08:01

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20200318_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='hruser',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hruser',
            name='photo',
            field=models.ImageField(default='user-photos/default.png', upload_to=administration.models.user_photo_path),
        ),
    ]
