# Generated by Django 3.0.3 on 2020-04-15 12:23

import administration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auto_20200320_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hruser',
            options={'managed': True, 'ordering': ['last_name', 'first_name'], 'verbose_name': 'HRUser', 'verbose_name_plural': 'HRUsers'},
        ),
        migrations.RemoveField(
            model_name='departament',
            name='parent',
        ),
        migrations.AddField(
            model_name='hruser',
            name='departments',
            field=models.ManyToManyField(to='administration.Departament'),
        ),
        migrations.AlterField(
            model_name='hruser',
            name='photo',
            field=models.ImageField(blank=True, default='user-photos/default.png', upload_to=administration.models.user_photo_path),
        ),
    ]
