# Generated by Django 3.0.3 on 2020-04-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20200415_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.RenameField(
            model_name='hruser',
            old_name='departments',
            new_name='departaments',
        ),
    ]
