# Generated by Django 3.0.3 on 2020-05-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20200416_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hruser',
            name='departaments',
            field=models.ManyToManyField(blank=True, to='administration.Departament'),
        ),
    ]
