# Generated by Django 3.0.3 on 2020-05-03 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChooseeQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=512)),
            ],
            options={
                'verbose_name': 'MultiChooseeQuiz',
                'verbose_name_plural': 'MultiChooseeQuizzes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('desciption', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('max_count', models.PositiveIntegerField(default=None, null=True)),
                ('is_shuffle', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SingleChooseQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=512)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire')),
            ],
            options={
                'verbose_name': 'SingleChooseQuiz',
                'verbose_name_plural': 'SingleChooseQuizzes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SingleChooseVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=128)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.SingleChooseQuiz')),
            ],
            options={
                'verbose_name': 'SingleChooseVariant',
                'verbose_name_plural': 'SingleChooseVariants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MultiChooseeVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=128)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.MultiChooseeQuiz')),
            ],
            options={
                'verbose_name': 'MultiChooseeVariant',
                'verbose_name_plural': 'MultiChooseeVariants',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='multichooseequiz',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire'),
        ),
        migrations.CreateModel(
            name='ArbitraryQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=512)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire')),
            ],
            options={
                'verbose_name': 'ArbitraryQuiz',
                'verbose_name_plural': 'ArbitraryQuizzes',
                'managed': True,
            },
        ),
    ]
