# Generated by Django 3.0.3 on 2020-05-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20200503_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlechoosevariant',
            options={'managed': True, 'ordering': ['order', 'variant'], 'verbose_name': 'SingleChooseVariant', 'verbose_name_plural': 'SingleChooseVariants'},
        ),
        migrations.AddField(
            model_name='singlechoosequiz',
            name='right',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singlechoosevariant',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='singlechoosevariant',
            name='variant',
            field=models.TextField(max_length=256),
        ),
    ]
