# Generated by Django 3.0.3 on 2020-05-05 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20200505_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitraryquiz',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrary_quizzes', to='questionnaire.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='multichooseequiz',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_quizzes', to='questionnaire.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='singlechoosequiz',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_quizzes', to='questionnaire.Questionnaire'),
        ),
    ]
