# Generated by Django 3.0.3 on 2020-05-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20200505_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitraryquiz',
            name='right',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='multichooseequiz',
            name='right',
            field=models.SmallIntegerField(default=0),
        ),
    ]
