# Generated by Django 3.0.3 on 2020-05-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20200505_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'managed': True, 'ordering': ['name', 'desciption'], 'verbose_name': 'Questionnaire', 'verbose_name_plural': 'Questionnaires'},
        ),
        migrations.AlterField(
            model_name='multichooseevariant',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='questionnaire.MultiChooseeQuiz'),
        ),
        migrations.AlterField(
            model_name='singlechoosevariant',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='questionnaire.SingleChooseQuiz'),
        ),
    ]
