# Generated by Django 3.0.3 on 2020-05-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_auto_20200506_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multichooseevariant',
            options={'managed': True, 'ordering': ['order', 'variant'], 'verbose_name': 'MultiChooseeVariant', 'verbose_name_plural': 'MultiChooseeVariants'},
        ),
        migrations.AddField(
            model_name='multichooseevariant',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='desciption',
            field=models.TextField(blank=True),
        ),
    ]
