# Generated by Django 3.0.3 on 2020-05-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20200507_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichooseevariant',
            name='right',
            field=models.BooleanField(default=False),
        ),
    ]
