# Generated by Django 3.0.6 on 2020-05-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20200503_1328'),
        ('questionnaire', '0013_auto_20200507_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='close_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='groups',
            field=models.ManyToManyField(null=True, to='administration.Departament'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='open_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='test_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='arbitraryquiz',
            name='order',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='multichoosequiz',
            name='order',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='multichoosevariant',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=-1),
        ),
        migrations.AlterField(
            model_name='singlechoosequiz',
            name='order',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='singlechoosevariant',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=-1),
        ),
    ]
