# Generated by Django 3.0.6 on 2020-05-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20200503_1328'),
        ('questionnaire', '0014_auto_20200510_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='close_date',
            new_name='close_datetime',
        ),
        migrations.RenameField(
            model_name='questionnaire',
            old_name='open_date',
            new_name='open_datetime',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='groups',
            field=models.ManyToManyField(to='administration.Departament'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='test_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
