# Generated by Django 3.0.6 on 2020-05-14 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaire', '0016_auto_20200513_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('end_datetime', models.DateTimeField()),
                ('is_complite', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MultiChooseAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=-1)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_answers', to='questionnaire.Answer')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.MultiChooseQuiz')),
            ],
            options={
                'verbose_name': 'MultiChooseAnswer',
                'verbose_name_plural': 'MultiChooseAnswers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SingleChooseAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=-1)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_answers', to='questionnaire.Answer')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.SingleChooseQuiz')),
                ('right', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.SingleChooseVariant')),
            ],
            options={
                'verbose_name': 'SingleChooseAnswer',
                'verbose_name_plural': 'SingleChooseAnswers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MultiChooseAnswerVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.MultiChooseAnswer')),
                ('right', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.MultiChooseVariant')),
            ],
            options={
                'verbose_name': 'MultiChooseAnswerVariant',
                'verbose_name_plural': 'MultiChooseAnswerVariants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArbitraryAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(default=-1)),
                ('right', models.TextField(max_length=512)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrary_answers', to='questionnaire.Answer')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.ArbitraryQuiz')),
            ],
            options={
                'verbose_name': 'ArbitraryAnswer',
                'verbose_name_plural': 'ArbitraryAnswers',
                'managed': True,
            },
        ),
    ]
