# Generated by Django 3.0.6 on 2020-05-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0017_answer_arbitraryanswer_multichooseanswer_multichooseanswervariant_singlechooseanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quiz',
            new_name='questionnaire',
        ),
        migrations.AlterField(
            model_name='multichooseanswervariant',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='questionnaire.MultiChooseAnswer'),
        ),
    ]
