# Generated by Django 3.0.6 on 2020-05-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_auto_20200514_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='step',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
