# Generated by Django 3.0.6 on 2020-05-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0019_auto_20200515_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arbitraryanswer',
            old_name='quiz',
            new_name='root',
        ),
        migrations.RenameField(
            model_name='multichooseanswer',
            old_name='quiz',
            new_name='root',
        ),
        migrations.RenameField(
            model_name='singlechooseanswer',
            old_name='quiz',
            new_name='root',
        ),
    ]
