# Generated by Django 3.0.6 on 2020-05-17 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0022_answer_max_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichooseanswervariant',
            name='right',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.MultiChooseVariant'),
        ),
    ]
