# Generated by Django 3.0.6 on 2020-05-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0023_auto_20200517_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlechooseanswer',
            name='right',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.SingleChooseVariant'),
        ),
    ]
