# Generated by Django 3.0.6 on 2020-05-20 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0024_auto_20200517_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoosequiz',
            name='method',
            field=models.CharField(choices=[('sum', 'Суммирование'), ('scl', 'Масштабирование')], default='sum', max_length=3),
        ),
        migrations.AddField(
            model_name='multichoosequiz',
            name='scale_value',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='multichoosevariant',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='singlechoosevariant',
            name='value',
            field=models.SmallIntegerField(default=0),
        ),
    ]
