# Generated by Django 3.0.6 on 2020-05-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0026_auto_20200522_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoosevariant',
            name='order',
            field=models.SmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='multichoosevariant',
            name='variant',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='singlechoosevariant',
            name='order',
            field=models.SmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='singlechoosevariant',
            name='variant',
            field=models.TextField(default='', max_length=256),
        ),
    ]
